### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Pikaronga** [HalfloveJAR/Daily-Rewards#1]
https://pastebin.com/vgUhRPbz

Plugin does not enable. Latest version Daily Rewards 1.3.7e

Purpur 1.16.5 (Latest build)

**Comment by LuuckA21** [comment]
With PaperMC (build 678 or above) plugin does not work.
![image](https://user-images.githubusercontent.com/50712503/119395804-562fe480-bcd4-11eb-81a5-3d84bb646fcb.png)

**Comment by HalfloveJAR** [comment]
Thanks for bringing this to my attention, I believe I have fixed the issue (I was compiling the plugin under the wrong JDK version).
